name: Run commit transcripts

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Commit changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update transcripts"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}