# .github/workflows/main.yml

name: Run RSS fetcher

on:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ffmpeg
      run: |
        sudo apt update
        sudo apt install ffmpeg
    - name: Run RSS fetcher
      run: python main.py

    - id: commit
      name: Commit changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git diff-index --quiet HEAD || echo ::set-output name=changed::true && git commit -m "Update transcripts"

    - name: Push changes
      if: steps.commit.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}