# .github/workflows/main.yml

name: Run RSS fetcher

on:
  push:
    paths: 'main.py'
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run RSS fetcher
      run: python main.py